---
# vars file for pyenv
enable_auto_completion: true
pyenv_update: 'no'

# https://github.com/pyenv/pyenv/wiki/Home/f3ebc17f67ba23e05771fd78468cd1cd03204fc8#suggested-build-environment
debian_deps:
  - make
  - build-essential
  - libssl-dev
  - zlib1g-dev
  - libbz2-dev
  - libreadline-dev
  - libsqlite3-dev
  - wget
  - curl
  - llvm
  - libncurses5-dev
  - xz-utils
  - tk-dev
  - libxml2-dev
  - libxmlsec1-dev
  - libffi-dev
  - liblzma-dev
  - git

# https://github.com/pyenv/pyenv/wiki/Home/f3ebc17f67ba23e05771fd78468cd1cd03204fc8#suggested-build-environment
redhat_deps:
  - make
  - gcc
  - zlib-devel
  - bzip2
  - bzip2-devel
  - readline-devel
  - sqlite
  - sqlite-devel
  - openssl-devel
  - tk-devel
  - libffi-devel
  - git
